package kth.nova.overloadalert.data.remote

import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import retrofit2.Response
import java.util.TimeZone

/**
 * Repository responsible for interacting with the Google Calendar API.
 *
 * This class handles operations related to fetching, creating, and managing calendars and
 * their associated events on a remote Google Calendar service. It acts as an abstraction
 * layer over the [GoogleCalendarApiService], executing network requests on the IO dispatcher.
 *
 * Key functionalities include:
 * - Retrieving or creating a specific calendar by name (summary).
 * - Creating, updating (patching), retrieving, and deleting calendar events.
 *
 * @property googleCalendarApiService The Retrofit service interface for Google Calendar API calls.
 */
class GoogleCalendarRepository(
    private val googleCalendarApiService: GoogleCalendarApiService
) {

    // --- Calendar Methods ---

    suspend fun getOrCreateCalendar(summary: String): String? = withContext(Dispatchers.IO) {
        try {
            val calendarId = findCalendarByName(summary)
            if (calendarId != null) {
                return@withContext calendarId
            }
            return@withContext createCalendar(summary)
        } catch (e: Exception) {
            Log.e("GoogleCalendarRepository", "Error getting or creating calendar", e)
            return@withContext null
        }
    }

    private suspend fun findCalendarByName(summary: String): String? {
        val calendars = googleCalendarApiService.getCalendarList()
        return calendars.items.find { it.summary == summary }?.id
    }

    private suspend fun createCalendar(summary: String): String? {
        val calendar = GoogleCalendar(
            summary = summary,
            description = "Training plan generated by OverloadAlert",
            timeZone = TimeZone.getDefault().id
        )
        val createdCalendar = googleCalendarApiService.createCalendar(calendar)
        return createdCalendar.id
    }

    // --- Event Methods ---

    suspend fun createEvent(calendarId: String, event: GoogleCalendarEvent): GoogleCalendarEvent = withContext(Dispatchers.IO) {
        googleCalendarApiService.createEvent(calendarId, event)
    }

    suspend fun patchEvent(calendarId: String, eventId: String, event: GoogleCalendarEvent): GoogleCalendarEvent = withContext(Dispatchers.IO) {
        googleCalendarApiService.patchEvent(calendarId, eventId, event)
    }

    suspend fun getEvent(calendarId: String, eventId: String): GoogleCalendarEvent = withContext(Dispatchers.IO) {
        googleCalendarApiService.getEvent(calendarId, eventId)
    }

    suspend fun deleteEvent(calendarId: String, eventId: String): Response<Unit> = withContext(Dispatchers.IO) {
        googleCalendarApiService.deleteEvent(calendarId, eventId)
    }
}